### PR TITLE
Refactor TMP117 to use shorter function names

### PR DESCRIPTION
**Pull request by ojousima**

### CODE REVIEW

**Comment by DG12** [comment]
shorter is so much better

**Review by DG12 — COMMENTED** [review]
use shorter function names  
and other little bugs

**Review by DG12 — COMMENTED** [review]
Why do you add  a "U" to unsigned integers and put them in  parens ??

**Comment by DG12** [comment]
Can you explain this complaint from  SonarCloud

```
532        else if ( ~~~1~~~  (RD_SENSOR_DSP_LAST == *dsp)
533               || ~~~2~~~ (RD_SENSOR_CFG_DEFAULT == *dsp
```

**Identical sub-expressions on both sides of operator "||".**

**Comment by ojousima** [comment]
> Why do you add a "U" to unsigned integers and put them in parens ?? 

In macros? Adding U makes them explicitly `unsigned int`. Having parenthesis around macro constants is a good practice, even though it's not really necessary for single constants. 

> else if ( ~~~1~~~  (RD_SENSOR_DSP_LAST == *dsp)
>             || ~~~2~~~ (RD_SENSOR_CFG_DEFAULT == *dsp

RD_SENSOR_DSP_LAST equals to RD_SENSOR_CFG_DEFAULT. Default could be something else in future, so it is checked separately.

**Comment by DG12** [comment]
Should the 100 or rather 1000 be a  #define ?

in file /ruuvi_nrf5_sdk15_i2c
 function rd_status_t ri_i2c_init

146  ri_delay_us (100);

**Comment by ojousima** [comment]
> Should the 100 or rather 1000 be a #define ?

Yes, magic constants are a bad practice. That's probably flagged by SonarCloud

**Comment by DG12** [comment]
What's a NRF_FIX_TWI_ISSUE_219 ? or 209?

**Comment by DG12** [comment]
> > Should the 100 or rather 1000 be a #define ?
>
Along with a comment as to how you arrived at this value instead of another (100) value

Does this type of definition, which seems to be adjustable
(as opposed to something like TMP117_VALUE_ID 0x0117)
belong in the source.c file or the header file ?

**Comment by ojousima** [comment]
> What's a NRF_FIX_TWI_ISSUE_219

SCL stays LOW shorter time than required by spec at 400 kHz

> Does this type of definition, which seems to be adjustable (as opposed to something like TMP117_VALUE_ID 0x0117)
belong in the source.c file or the header file ?

Ideally it would be passed from the board definition. Practically I'm not going to bother with working that in, given that the saving would be 900 us per boot.

**Comment by DG12** [comment]
_Constants should come first in equality tests_

THIS IS AN EXCELLENT CASE WHERE FOLLOWING A CONVENTION MAKES TRERRRRRRRIBLE CODE ~

I HATE THIS!

**Comment by ojousima** [comment]
> But it is much worse where the test if for less than
(which is not the convention)
The condition has to be written backward.
ri_rtc_millis() > (start + BLOCKING_COMM_TIMEOUT_MS
In this case it's not even a constant but a function call.

Maybe yes, and it's harder to mix `>=` and `==` the same way `==` and `=` tend to get mixed. 

> The error:
Constants should come first in equality tests
is an example of an convention that causes people to write bad code.

I disagree. Subtle bugs where comparison and assignment are mixed cause enough problems to have a CWE: https://cwe.mitre.org/data/definitions/481.html .

**Comment by DG12** [comment]
Thanks for showing me the Common Weakness Enumeration

**Pull request merged**
